sudo: required
services:
  - docker

before_install:
  - docker build -t tapir79/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tapir79/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react" 
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-130763799244"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY_ID
  secret_access_key: 
    secure: "$AWS_SECRET_ACCESS_KEY_ID"